/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConformanceRouteImport } from './routes/conformance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangeReviewsReviewIdIndexRouteImport } from './routes/change-reviews/$reviewId/index'
import { Route as ChangeReviewsReviewIdGroupsGroupKeyRouteImport } from './routes/change-reviews/$reviewId/groups/$groupKey'
import { Route as PoliciesPolicyIdVersionsVersionIdRouteImport } from './routes/policies/$policyId/versions/$versionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConformanceRoute = ConformanceRouteImport.update({
  id: '/conformance',
  path: '/conformance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeReviewsReviewIdIndexRoute =
  ChangeReviewsReviewIdIndexRouteImport.update({
    id: '/change-reviews/$reviewId/',
    path: '/change-reviews/$reviewId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChangeReviewsReviewIdGroupsGroupKeyRoute =
  ChangeReviewsReviewIdGroupsGroupKeyRouteImport.update({
    id: '/change-reviews/$reviewId/groups/$groupKey',
    path: '/change-reviews/$reviewId/groups/$groupKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const PoliciesPolicyIdVersionsVersionIdRoute =
  PoliciesPolicyIdVersionsVersionIdRouteImport.update({
    id: '/policies/$policyId/versions/$versionId',
    path: '/policies/$policyId/versions/$versionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conformance': typeof ConformanceRoute
  '/login': typeof LoginRoute
  '/change-reviews/$reviewId/': typeof ChangeReviewsReviewIdIndexRoute
  '/change-reviews/$reviewId/groups/$groupKey': typeof ChangeReviewsReviewIdGroupsGroupKeyRoute
  '/policies/$policyId/versions/$versionId': typeof PoliciesPolicyIdVersionsVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conformance': typeof ConformanceRoute
  '/login': typeof LoginRoute
  '/change-reviews/$reviewId': typeof ChangeReviewsReviewIdIndexRoute
  '/change-reviews/$reviewId/groups/$groupKey': typeof ChangeReviewsReviewIdGroupsGroupKeyRoute
  '/policies/$policyId/versions/$versionId': typeof PoliciesPolicyIdVersionsVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conformance': typeof ConformanceRoute
  '/login': typeof LoginRoute
  '/change-reviews/$reviewId/': typeof ChangeReviewsReviewIdIndexRoute
  '/change-reviews/$reviewId/groups/$groupKey': typeof ChangeReviewsReviewIdGroupsGroupKeyRoute
  '/policies/$policyId/versions/$versionId': typeof PoliciesPolicyIdVersionsVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conformance'
    | '/login'
    | '/change-reviews/$reviewId/'
    | '/change-reviews/$reviewId/groups/$groupKey'
    | '/policies/$policyId/versions/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conformance'
    | '/login'
    | '/change-reviews/$reviewId'
    | '/change-reviews/$reviewId/groups/$groupKey'
    | '/policies/$policyId/versions/$versionId'
  id:
    | '__root__'
    | '/'
    | '/conformance'
    | '/login'
    | '/change-reviews/$reviewId/'
    | '/change-reviews/$reviewId/groups/$groupKey'
    | '/policies/$policyId/versions/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConformanceRoute: typeof ConformanceRoute
  LoginRoute: typeof LoginRoute
  ChangeReviewsReviewIdIndexRoute: typeof ChangeReviewsReviewIdIndexRoute
  ChangeReviewsReviewIdGroupsGroupKeyRoute: typeof ChangeReviewsReviewIdGroupsGroupKeyRoute
  PoliciesPolicyIdVersionsVersionIdRoute: typeof PoliciesPolicyIdVersionsVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conformance': {
      id: '/conformance'
      path: '/conformance'
      fullPath: '/conformance'
      preLoaderRoute: typeof ConformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-reviews/$reviewId/': {
      id: '/change-reviews/$reviewId/'
      path: '/change-reviews/$reviewId'
      fullPath: '/change-reviews/$reviewId/'
      preLoaderRoute: typeof ChangeReviewsReviewIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-reviews/$reviewId/groups/$groupKey': {
      id: '/change-reviews/$reviewId/groups/$groupKey'
      path: '/change-reviews/$reviewId/groups/$groupKey'
      fullPath: '/change-reviews/$reviewId/groups/$groupKey'
      preLoaderRoute: typeof ChangeReviewsReviewIdGroupsGroupKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$policyId/versions/$versionId': {
      id: '/policies/$policyId/versions/$versionId'
      path: '/policies/$policyId/versions/$versionId'
      fullPath: '/policies/$policyId/versions/$versionId'
      preLoaderRoute: typeof PoliciesPolicyIdVersionsVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConformanceRoute: ConformanceRoute,
  LoginRoute: LoginRoute,
  ChangeReviewsReviewIdIndexRoute: ChangeReviewsReviewIdIndexRoute,
  ChangeReviewsReviewIdGroupsGroupKeyRoute:
    ChangeReviewsReviewIdGroupsGroupKeyRoute,
  PoliciesPolicyIdVersionsVersionIdRoute:
    PoliciesPolicyIdVersionsVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
