import { fileURLToPath } from 'node:url';

export const REQUIRED_SECTIONS = ['Summary', 'Changes', 'Testing', 'Checklist'] as const;

export type RequiredSection = (typeof REQUIRED_SECTIONS)[number];

const FORBIDDEN_PATTERNS: ReadonlyArray<{ readonly label: string; readonly pattern: RegExp }> = [
  { label: 'internal ticket label M0x', pattern: /\bM0[1-9]\b/ },
  { label: 'internal ticket label M1x', pattern: /\bM1[0-6]\b/ },
  { label: 'internal ticket label T0x', pattern: /\bT0[1-9]\b/ },
  { label: 'internal ticket label T1x/T2x', pattern: /\bT[12][0-9]\b/ },
  { label: 'orchestration branch prefix fm/', pattern: /\bfm\// },
  { label: 'orchestration context', pattern: /firstmate|crewmate/ },
  { label: 'Co-Authored-By footer', pattern: /Co-Authored-By/i },
  { label: 'Generated by attribution', pattern: /Generated by/i },
  { label: 'model id prefix', pattern: /claude-(opus|sonnet|fable|haiku)-/i },
  {
    label: 'agent source branch prefix',
    pattern: /\b(ai|claude|codex|copilot|cursor)\//,
  },
];

const CHECKLIST_ITEM = /^-\s*\[([ xX])\]\s+.+/;

export type ValidatePullRequestResult =
  | { readonly ok: true }
  | { readonly ok: false; readonly failures: readonly string[] };

function stripHtmlComments(text: string): string {
  return text.replace(/<!--[\s\S]*?-->/g, '');
}

function parseSectionCounts(body: string): Map<string, number> {
  const counts = new Map<string, number>();
  for (const line of body.split(/\r?\n/)) {
    const match = /^##\s+(.+?)\s*$/.exec(line);
    if (match?.[1]) {
      const name = match[1].trim();
      counts.set(name, (counts.get(name) ?? 0) + 1);
    }
  }
  return counts;
}

function parseSections(body: string): Map<string, string> {
  const sections = new Map<string, string>();
  const lines = body.split(/\r?\n/);
  let current: string | undefined;
  let buffer: string[] = [];

  const flush = (): void => {
    if (current !== undefined) {
      sections.set(current, buffer.join('\n'));
    }
    buffer = [];
  };

  for (const line of lines) {
    const match = /^##\s+(.+?)\s*$/.exec(line);
    if (match?.[1]) {
      flush();
      current = match[1].trim();
      continue;
    }
    if (current !== undefined) {
      buffer.push(line);
    }
  }

  flush();
  return sections;
}

function nonEmptyLines(content: string): string[] {
  return stripHtmlComments(content)
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
}

function checklistItems(content: string): Array<'checked' | 'unchecked'> {
  const items: Array<'checked' | 'unchecked'> = [];
  for (const line of content.split(/\r?\n/)) {
    const match = CHECKLIST_ITEM.exec(line.trim());
    if (match?.[1]) {
      items.push(match[1].toLowerCase() === 'x' ? 'checked' : 'unchecked');
    }
  }
  return items;
}

function findForbiddenPatterns(text: string): string[] {
  const hits: string[] = [];
  for (const { label, pattern } of FORBIDDEN_PATTERNS) {
    if (pattern.test(text)) {
      hits.push(label);
    }
  }
  return hits;
}

export function validatePullRequest(input: {
  readonly title: string | null | undefined;
  readonly body: string | null | undefined;
}): ValidatePullRequestResult {
  const failures: string[] = [];
  const title = input.title?.trim() ?? '';
  const body = input.body ?? '';

  if (title.length === 0) {
    failures.push('rule 4: title must not be empty');
  }

  if (body.trim().length === 0) {
    failures.push('rule 2: body must not be empty');
    return { ok: false, failures };
  }

  const headingCounts = parseSectionCounts(body);
  for (const name of REQUIRED_SECTIONS) {
    const count = headingCounts.get(name) ?? 0;
    if (count !== 1) {
      failures.push(`rule 1: ${name}: required heading "## ${name}" must appear exactly once`);
    }
  }

  const sections = parseSections(body);

  for (const name of REQUIRED_SECTIONS) {
    if ((headingCounts.get(name) ?? 0) !== 1) {
      continue;
    }

    const content = sections.get(name) ?? '';

    if (name === 'Checklist') {
      const items = checklistItems(content);
      if (items.length !== 3) {
        failures.push(
          `rule 3: Checklist: expected exactly 3 checklist items, found ${String(items.length)}`,
        );
      } else if (items.some((item) => item === 'unchecked')) {
        failures.push('rule 3: Checklist: every checklist item must be checked (- [x])');
      }
      continue;
    }

    if (nonEmptyLines(content).length === 0) {
      failures.push(`rule 2: ${name}: section body must include content beyond HTML comments`);
    }
  }

  for (const hit of findForbiddenPatterns(title)) {
    failures.push(`rule 4: title contains forbidden pattern (${hit})`);
  }
  for (const hit of findForbiddenPatterns(body)) {
    failures.push(`rule 4: body contains forbidden pattern (${hit})`);
  }

  if (failures.length === 0) {
    return { ok: true };
  }

  return { ok: false, failures };
}

function main(): void {
  const title = process.env.PR_TITLE;
  const body = process.env.PR_BODY;

  if (title === undefined || body === undefined) {
    process.stderr.write('PR_TITLE and PR_BODY environment variables are required.\n');
    process.exit(1);
  }

  const result = validatePullRequest({ title, body });
  if (result.ok) {
    return;
  }

  for (const failure of result.failures) {
    process.stderr.write(`${failure}\n`);
  }
  process.exit(1);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
